#ifndef _MTK_ECHO_ASSERT_UNWIND_H
#define _MTK_ECHO_ASSERT_UNWIND_H

#include <linux/types.h>

#define ECHO_ASSERT_UNWIND_E0 0xE0
#define ECHO_ASSERT_UNWIND_E1 0xE1
#define ECHO_ASSERT_UNWIND_E2 0xE2
#define ECHO_ASSERT_UNWIND_E3 0xE3
#define ECHO_ASSERT_UNWIND_E4 0xE4
#define ECHO_ASSERT_UNWIND_E5 0xE5
#define ECHO_ASSERT_UNWIND_E6 0xE6
#define ECHO_ASSERT_UNWIND_E7 0xE7
#define ECHO_ASSERT_UNWIND_E8 0xE8
#define ECHO_ASSERT_UNWIND_E9 0xE9

#define ECHO_START_FREE_CALLER_BEFORE 0x90
#define ECHO_START_FREE_CNM_ENTER 0x91
#define ECHO_START_FREE_DYNAMIC_BEFORE 0x92
#define ECHO_START_FREE_DYNAMIC_AFTER 0x93
#define ECHO_START_FREE_POOL_LOCK_WAIT 0x94
#define ECHO_START_FREE_POOL_LOCK_HELD 0x95
#define ECHO_START_FREE_AFTER_CNM 0x96
#define ECHO_START_FREE_CMD_LOCK_WAIT 0x97
#define ECHO_START_FREE_CMD_LOCK_HELD 0x98
#define ECHO_START_FREE_CMD_LOCK_RELEASED 0x99

#define ECHO_BT_FIRST_B0 0x60
#define ECHO_BT_FIRST_B1 0x61
#define ECHO_BT_FIRST_B2 0x62
#define ECHO_BT_FIRST_B3 0x63

#define ECHO_BT_INNER_B4 0x64
#define ECHO_BT_INNER_B5 0x65
#define ECHO_BT_INNER_B6 0x66
#define ECHO_BT_INNER_B7 0x67
#define ECHO_BT_INNER_B8 0x68
#define ECHO_BT_INNER_B9 0x69
#define ECHO_BT_INNER_BA 0x6A
#define ECHO_BT_INNER_BB 0x6B

#define ECHO_FW_CLEANUP_F0 0xF0
#define ECHO_FW_CLEANUP_F1 0xF1
#define ECHO_FW_CLEANUP_F2 0xF2
#define ECHO_FW_CLEANUP_F3 0xF3
#define ECHO_FW_CLEANUP_F4 0xF4
#define ECHO_FW_CLEANUP_F5 0xF5
#define ECHO_FW_CLEANUP_F6 0xF6
#define ECHO_FW_CLEANUP_F7 0xF7
#define ECHO_FW_CLEANUP_F8 0xF8
#define ECHO_FW_CLEANUP_F9 0xF9
#define ECHO_FW_CLEANUP_FA 0xFA
#define ECHO_FW_CLEANUP_FB 0xFB
#define ECHO_FW_CLEANUP_FC 0xFC
#define ECHO_FW_CLEANUP_FD 0xFD
#define ECHO_FW_CLEANUP_FE 0xFE

#define ECHO_RX_CALLBACK_BUDGET 2
#define ECHO_RX_BYTE_BUDGET 4096

extern bool echo_fw_asserted(void);
extern bool echo_wlan_assert_snapshot_complete(void);
extern bool echo_start_free_trace_active(void *pvMemory);

#endif
